### ISSUE TITLE
安卓平台部署

### ISSUE THREAD

**Issue by Clara2333333** [Whu-wxy/yolov5_deepsort_ncnn_qt#4]
您好，请问本项目中的cpp和.h文件可以放进Android studio项目中的/main/jni，用以在安卓端使用deepsort模型吗

**Comment by Whu-wxy** [comment]
可以的

**Comment by Clara2333333** [comment]
> 可以的

好哒~非常感谢~

**Comment by Clara2333333** [comment]
> 可以的

好哒~非常感谢！！！

**Comment by Clara2333333** [comment]
> 可以的

您好，请问我如果已经在Android studio项目中部署过了自己训练好的目标检测器的ncnn模型，只是需要加一个跟踪器。我是应该将DeepAppearanceDescriptor文件夹中的deepsort.cpp和deeport.h放进/main/jni中，然后在activity中可调用。还是我需要将本项目所有文件整个放进/main/jni，才能对deepsort进行调用，加到我原有的目标检测器之后呢

**Comment by Whu-wxy** [comment]
用你的接deeport
