### ISSUE TITLE
整个项目放进Android studio项目出现模块找不到的问题

### ISSUE THREAD

**Issue by Clara2333333** [Whu-wxy/yolov5_deepsort_ncnn_qt#5]
您好，可以请教一个问题吗，我将该项目完整放进了android studio项目中的\app\src\main\jni，并且在cmakelist.txt修改add_library，添加了此项目中的cpp文件名和.h文件名，但是没有修改target_link_libraries。
在android studio中编译的时候，出现了很多模块找不到的情况。例如'QString' file not found，'ncnn/net.h' file not found，'opencv2/dnn/dnn.hpp' file not found，No member named 'dnn' in namespace 'cv'，Expected namespace name
请问是不是我的模块依赖有问题，需要修改target_link_libraries？或者是我安装的opencv或者ncnn有问题？目前我在\app\src\main\jni下放的版本为：ncnn-20221128-android-vulkan和opencv-mobile-4.6.0-android。不知道是不是我的这两个版本中不包含net.h和dnn.hpp之类，请问您用的是什么版本呢
想请教一下我该如何解决这些文件找不到的问题。非常感谢！

**Comment by Whu-wxy** [comment]
需要添加的库：Qt, opencv, ncnn

**Comment by Clara2333333** [comment]
您好，请问Android studio应该如何引入QT库呢，我查到的QT安卓开发都是用的QT creator编译器，没有关于Android studio引入qt库的教程，请问可以向您请教Android studio应该如何引入QT库吗，我第一次用安卓调用深度学习模型，不是特别熟悉这一块。非常非常感谢您的帮助，祝您一切顺利~


&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Whu-wxy/yolov5_deepsort_ncnn_qt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月28日(星期三) 上午10:02
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Whu-wxy/yolov5_deepsort_ncnn_qt] 整个项目放进Android studio项目出现模块找不到的问题 (Issue #5)





 
需要添加的库：Qt, opencv, ncnn
